### ISSUE TITLE
HTTP Response Splitting vulnerability identified

### ISSUE THREAD

**Issue by boxa99** [gin-contrib/timeout#42]
Snyk has identified an issue with the github.com/gin-gonic/gin module, versions < 1.7.7

https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMGINGONICGIN-1041736

github.com/gin-contrib/timeout@v0.0.3 is depending on github.com/gin-gonic/gin@v1.7.2 and is being flagged in my scans. Please update your dependency when you have time

Kind Regards,
Tom

**Comment by pspencer-arculus** [comment]
Hey boxa99, in the go.mod it looks like the dependency was updated to 1.8.1.

**Comment by appleboy** [comment]
https://github.com/gin-contrib/timeout/blob/f338d36f1dca37a4e2e2b28e9a5e5bde18e67493/go.mod#L6
