### ISSUE TITLE
Combined http results

### ISSUE THREAD

**Issue by Hongbo-Miao** [gin-contrib/timeout#7]
I have a very simple Gin server.

```go
func Health(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{
		"status": "ok",
	})
}

r := gin.Default()
r.GET("/", timeout.New(
	timeout.WithTimeout(1000*time.Microsecond),
	timeout.WithHandler(controllers.Health),
))
err := r.Run(":" + config.Port)
```

However, if I click multiple times, sometimes I will get results like with previous call results and be combined together:

![image](https://user-images.githubusercontent.com/3375461/127874245-bb0c0c2f-ec7a-45d8-bd62-df8508ab6709.png)

And sometimes not.

Any idea? Thanks

**Comment by appleboy** [comment]
Fixed in #13
